### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by ThrowYouARem** [bharath5673/StrongSORT-YOLO#11]
I encountered this error when I used the camera.

Traceback (most recent call last):
  File "track_v7.py", line 386, in <module>
    detect()
  File "track_v7.py", line 189, in detect
    curr_frames[i] = im0
IndexError: list assignment index out of range

**Comment by yazzmann** [comment]
@ThrowYouARem , 
I ran into the same situation 

File "track_v7.py", line 386, in
detect()
File "track_v7.py", line 189, in detect
curr_frames[i] = im0
IndexError: list assignment index out of range

**Comment by yuezhilanyi** [comment]
@yazzmann @ThrowYouARem 
modify file "yolov7/utils/datasets.py", line 344, will solve this issue
from 
`return 0`
to 
`return len(self.sources)`
