### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by mamounjamous** [bharath5673/StrongSORT-YOLO#12]
Trying to run over yolov5 and it runs with no issue, however, running over yolov7 gives an issue:

(strongsort) C:\Users\Lenovo>cd \projects\strongsort

(strongsort) C:\projects\strongsort>python track_v7.py --source 0 --yolo-weights weights/yolov7-tiny.pt --classes 0
Namespace(yolo_weights=['weights/yolov7-tiny.pt'], strong_sort_weights=WindowsPath('C:/projects/strongsort/weights/osnet_x0_25_msmt17.pt'), config_strongsort='strong_sort/configs/strong_sort.yaml', source='0', img_size=640, conf_thres=0.25, iou_thres=0.45, device='', show_vid=True, save_txt=False, save_img=False, save_conf=False, nosave=True, save_vid=False, classes=[0], agnostic_nms=False, augment=False, update=False, project='runs/track', exp_name='exp', exist_ok=False, trace=False, line_thickness=1, hide_labels=False, hide_conf=False, hide_class=False, count=False, draw=False)
YOLOR  2022-11-21 torch 1.13.0+cpu CPU

Fusing layers...
Model Summary: 200 layers, 6219709 parameters, 229245 gradients
1/1: 0...  success (640x480 at 30.00 FPS).

Traceback (most recent call last):
  File "C:\projects\strongsort\track_v7.py", line 386, in <module>
    detect()
  File "C:\projects\strongsort\track_v7.py", line 189, in detect
    curr_frames[i] = im0
IndexError: list assignment index out of range

(strongsort) C:\projects\strongsort>

Tried few quick solutions but no luck so far ...

**Comment by Elhadji411** [comment]
I have the same error but no Idea how to fixe this.i need help🙏
